version: '3.4'
services:
  canon-printer:
    build:
      context: .
      network: host
    volumes:
      - ~/canon-printer-server/cups-spool/:/cups-spool/
    tty: true
    stdin_open: true
    network_mode: host
    restart: always
